### ISSUE TITLE
“此应用无法在你的电脑上运行”

### ISSUE THREAD

**Issue by SoYuCry** [jinaojakezhang/FEDFEMBioheatDeform#1]
![image](https://user-images.githubusercontent.com/87529679/221140442-9cba58f1-0cea-4ba0-8b53-c1b48df64f64.png)

**Comment by jinaojakezhang** [comment]
Please provide more details about this issue.
You can also refer to the "Environment", "How to build", and "How to use" sections of this repo.

**Comment by SoYuCry** [comment]
![image](https://user-images.githubusercontent.com/87529679/221150721-a7d3f623-cacb-4d1c-8a9a-dc07e6154f07.png)
Although that I didn't find where to open OpenMV, I still build the solution successfully. But I can't open the .exe with cmd, even in  the administrator mode. I check how to fix it on Google, and use Dependency Walker to open it. It shows that "Error: At least one file was not a 32-bit or 64-bit Windows module ."

**Comment by SoYuCry** [comment]
I have knew my mistake. I just chose debug/x86 mode. But after I changed it to realease/x64 mode, I get the .exe. When I click it or  run it in cmd, no reactions exists. And I also have a question that I didn't know where to place the .txt.

**Comment by jinaojakezhang** [comment]
> I have knew my mistake. I just chose debug/x86 mode. But after I changed it to realease/x64 mode, I get the .exe. When I click it or run it in cmd, no reactions exists. And I also have a question that I didn't know where to place the .txt.

Please see "How to use" 1. You need to run from cmd and place the .txt in the same folder where your .exe is.

**Comment by SoYuCry** [comment]
I download the wrong versions of visual studio.
